---
# These are supported funding model platforms
github: cooljeanius
patreon: EricGallager
ko_fi: maraanelang # (varies depending on which repo this is)
liberapay: Wesnoth
open_collective: cooljeanius
